edition = "2024"
max_width = 99
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 99
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
binop_separator = "Front"
